[ Portfolio: mobile menu ] Microverse Project
mr-abdellah/my-portfolio pull request #12
Opened 2022-05-09 12:51 UTC by mr-abdellah

In this project we added a dynamic menu , it open and close when the user click on the hamburger menu icon and if the user follow a link on it also

2022-05-09 19:58 UTC, mr-abdellah commented
hello, please , I got stuck about how to make parentheses between arrow function argument, that is my only problem actually

2022-05-09 20:51 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @mr-abdellah, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![768070f3-bc9a-4aba-b8bc-25793e00ea1e_text](https://user-images.githubusercontent.com/70269507/159483175-2f61461d-b352-4cb4-98f8-b173e05ab5ff.gif)

## Highlights
✔️ All linters are passing
✔️ Professional readme
✔️ Correct Gitflow
✔️ Great job in implementing the mobile menu correctly in the first attempt 👏 

## Required 
- [ ] Kindly update your readme with collaborator details and with steps to set up your project locally.
- [ ] _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-09 20:51 UTC, sja-thedude commented on stylesheet.css
> +  height: 430px;
- [ ] Kindly make sure to add the mobile menu height that covers the entire page as per the Figma design.
- [ ] Kindly follow the correct spacing, font size and font colour for the mobile menu options.

Figma design:

<img width="318" alt="Screenshot 2022-05-09 at 11 41 15 PM" src="https://user-images.githubusercontent.com/70269507/167494487-2255ac8c-0914-49f2-843c-f178f6ace178.png">

Your design:

https://user-images.githubusercontent.com/70269507/167494961-57665894-8f09-44e9-87a3-4d8366a41f34.mov

2022-05-10 08:09 UTC, sja-thedude approved these changes
## Project Approved 👍 

Hi @mr-abdellah, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 08:11 UTC, merged