Portfolio: mobile version [ Microverse Project ]
mr-abdellah/my-portfolio pull request #3
Opened 2022-04-21 19:48 UTC by mr-abdellah

the final "Portfolio: mobile version" Microverse project result.

2022-04-21 21:01 UTC, gtekle requested changes
Hi @mr-abdellah , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there-01](https://user-images.githubusercontent.com/44057863/164551482-eeee23e6-a09f-4a4b-9eb7-a6c8305cd860.gif)

## Highlights
:heavy_check_mark: Clean and organized code
:heavy_check_mark: Nice UI
:heavy_check_mark: Good use of GitHub flow

## Required Changes ♻️
_Check the comments under the review._

- [ ] You should add all the sections from the README [template](https://github.com/microverseinc/readme-template/blob/master/README.md) provided by Microverse.

Please check the inline comments below.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-21 21:01 UTC, gtekle commented on index.html
> +    <div class="secondSection">
- [x] You should use `section` tag instead of `div` because it is semantically helpful for things such as SEO. You may refer this freecodecamp [article](https://www.freecodecamp.org/news/semantic-html5-elements) for more detailed explanation about HTML5 semantic tags.

2022-04-21 21:01 UTC, gtekle commented on index.html
> +                <p class="work-title">Multi-Post Stories<br>Gain+Glory</p>
- [x] You should use `<h3>` instead of `<p>` tag in here, because the content is heading and using `<h3>` here is semantically appropriate. (The reason why `<h3>` is because you have already used both `<h1>` & `<h2>` and it is not good practice to jump a level to use `<h4>`). Kindly apply the same fashion to all `project titles `under the works section.

2022-04-21 21:01 UTC, gtekle commented on index.html
> +                <button>See Project</button>
- [ Optional ] It is good practice to add the button's type property.

2022-04-21 21:01 UTC, gtekle commented on index.html
> +        <div class="about-me">
- [x] You should use `section` tag instead of `div` for the same semantic reason discussed above.

2022-04-21 21:01 UTC, gtekle commented on index.html
> +                don't hestiate to contact me.</h4>
- [x] You should use `<p>` tag instead of `<h4>` because the semantic meaning of the content is a paragraph and not a heading.

2022-04-21 21:01 UTC, gtekle commented on index.html
> +                    <p class="card-paragraph">Languages</p>
- [x] Here, you should use `<h4>` instead of `<p>` tag for the content is a sub-heading. Please refer the link for HTML5 semantic elements above.

2022-04-21 21:01 UTC, gtekle commented on index.html
> +                    <p class="card-paragraph">Frameworks</p>
- [x] You should `<h4>` tag instead of `<p>` here as well for the same reason mention above.

2022-04-21 21:01 UTC, gtekle commented on stylesheet.css
> +}
- [x] It is a requirement to use Flex-Box CSS layout to position the layout of the contents of each project. So, kindly use Flex-box here.
- [ Optional ] It is not a good practice to use fixed height and width for HTML elements. It makes your page non-responsive. So, please use percentage or other relative unit.

2022-04-22 09:20 UTC, vic778 approved these changes
Hi @mr-abdellah  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Charlie Brown](https://media.giphy.com/media/ZdO4NenDbsQNwUwKDB/giphy.gif)

## Highlights

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-22 09:22 UTC, merged