Making the portfolio responsive [Desktop & Mobile Version]
mr-abdellah/my-portfolio pull request #5
Opened 2022-04-27 13:17 UTC by mr-abdellah

This is the final result of making the [Portfolio: desktop version Project]
**### note that :**
-My website is a Desktop-first approach
- My media query is for 600px width

2022-04-27 14:00 UTC, ShadyShawkat requested changes
## Hi @mr-abdellah, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-27 14:00 UTC, ShadyShawkat commented on index.html
>          <header class="myHeader">
- [ ] Kindly make sure that the mobile version is displayed properly to match the Figma design. Currently, there's extra space to the right in the design which is likely caused by giving an element a fixed width so that it's taking more width than it should have.

![image](https://user-images.githubusercontent.com/62290545/165530281-822ba12b-778f-467c-a112-5ab6eab0aaf6.png)

2022-04-27 14:00 UTC, ShadyShawkat commented on stylesheet.css
> +  }
- [ ] Kindly use the right media query described [here](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/4_desktop_version.md#:~:text=(Desktop%3A%20768px%20or%20wider)) in the requirement. Also please use `min-width` instead of `max-width` so that the design is mobile first.
- [ ] Please make sure that the design matches the Figma design at width `768px` (if you're using `(min-width: 768px)`) which is the minimum width for desktop version.

2022-04-27 14:00 UTC, ShadyShawkat commented on index.html
>      <section class="secondSection">
- Please try to stick to the Figma design as much as possible, which includes.
   - [ ] Adjusting the font size of the header section text to match the Figma design.
   - [ ] Adding the "down-arrow" button to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/165535069-b2734727-284b-453a-a7b1-280aaffcc881.png) | ![image](https://user-images.githubusercontent.com/62290545/165535127-878c55e7-5525-4aa5-a78c-931815450904.png) |

2022-04-27 14:20 UTC, mr-abdellah commented on stylesheet.css
> +  }
hello, please bro I mentioned before that I started in the previous week with the desktop version and make it responsive with media query so do you want me to remake the whole project?

2022-04-28 07:22 UTC, mr-abdellah commented on stylesheet.css
> +  }
@ShadyShawkat

2022-04-28 11:58 UTC, topeogunleye approved these changes
### Hi @mr-abdellah, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
> 
> ## [Optional] suggestions:
>- [ ] From now on,please kindly make use of imperative mood in the subject line for your commit messages.
:x: Wrong
![Screenshot from 2022-04-28 12-55-24](https://user-images.githubusercontent.com/52934128/165747005-1b676d5e-5a0b-4f17-9373-f4d07b500d8a.png)
> ### Good Commit Messages:
>- [x]  Add fix for dark mode toggle state
>- [x] Update README file.
>- [x] Add styles to h1.
>
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 12:30 UTC, merged

2022-04-28 14:51 UTC, ShadyShawkat commented on stylesheet.css
> +  }
@mr-abdellah, I'm just following the project requirements, that's all.